name: Compile rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: fedora:latest
    

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust + Cargo
      run: dnf update && dnf install rustc cargo openssl openssl-devel --assumeyes
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
